function changeLanguage() {
    var languageSelect = document.getElementById('language');
    var language = languageSelect.options[languageSelect.selectedIndex].value;
    var textElement = document.getElementById('text');
    var textElement1 = document.getElementById('text1');
    var textElement2 = document.getElementById('text2');
    var textElement3 = document.getElementById('text3');
    var textElement4 = document.getElementById('text4');
    var textElement5 = document.getElementById('text5');
    var textElement6 = document.getElementById('text6');
    var textElement7 = document.getElementById('text7');
    var textElement8 = document.getElementById('text8');
    var textElement9 = document.getElementById('text9');
    var textElement10 = document.getElementById('text10');
    var textElement11 = document.getElementById('text11');
    var textElement12 = document.getElementById('text12');
    var textElement13 = document.getElementById('text13');
    var textElement14 = document.getElementById('text14');
    var textElement15 = document.getElementById('text15');
    var textElement16 = document.getElementById('text16');
    var textElement17 = document.getElementById('text17');
    var textElement18 = document.getElementById('text18');
    var textElement19 = document.getElementById('text19');
    var textElement20 = document.getElementById('text20');
    var textElement21 = document.getElementById('text21');
    var textElement22 = document.getElementById('text22');
    var textElementfooter = document.getElementById('footer');

    if (language === 'en') {
      textElement.innerText = 'Call Pwin'
      textElement1.innerText = 'Help Center'
      textElement2.innerText = 'Check Price Now'
      textElement3.innerText = 'Call Pwin for no more than 20 ฿ throughout the university.';
      textElement4.innerText = 'Get Started'
      textElement5.innerText = 'Convenient Safe and Standardized'
      textElement6.innerText = 'Pwin Calling Service is a service for Thammasat University Rangsit Center students to check Pwin prices within the university and is a platform for complaints. You can check Pwin prices or check Pwin information on this website.'
      textElement7.innerText = 'More details'
      textElement8.innerText = '3 Check'
      textElement9.innerText = 'Check the pick-up point'
      textElement10.innerText = 'You can view Pwin pick-up points at each point within the university.'
      textElement11.innerText = 'Check the price of the Pwin.'
      textElement12.innerText = 'You can check the price of Pwin from the pick-up point to various buildings within the university.'
      textElement13.innerText = 'Check the basic information of Pwin.'
      textElement14.innerText = 'Check the basic information of Pwin, such as Pwin ID number, queue number, and license plate number of Pwin.'
      textElement15.innerText = 'Service area'
      textElement16.innerText = 'Convenient'
      textElement17.innerText = 'You can check up to 3 things.'
      textElement18.innerText = 'Secure'
      textElement19.innerText = 'Register PWin as a yellow plate for every car and show it in the website system'
      textElement20.innerText = 'Standard'
      textElement21.innerText = 'Price is standard with PWin yellow label for every car.'
      textElement22.innerText = 'Complaint : '
      textElementfooter.innerText = '©️ 2025 Thammasat University Student Councils Home. All rights reserved.'
    } else if (language === 'th') {
      textElement.innerText = 'เรียกพี่วิน'
      textElement1.innerText = 'ศูนย์ช่วยเหลือ'
      textElement2.innerText = 'เช็คราคาตอนนี้'
      textElement3.innerText = 'เรียกพี่วินไม่เกิน 20 ฿ ทั่วมหาวิทยาลัย'
      textElement4.innerText = 'เริ่มต้น'
      textElement5.innerText = 'สะดวก ปลอดภัย มีมาตรฐาน'
      textElement6.innerText = 'บริการเช็คพี่วิน คือบริการสำหรับนักศึกษามหาวิทยาลัยธรรมศาตร์ศูนย์รังสิตในการเช็คราคาพี่วินเขียนภายในมหาวิทยาลัยและเป็นแพลตฟอร์มในการร้องเรียนโดยสามารถเช็คราคาพี่วินหรือเช็คข้อมูลพี่วินได้ภายในเว็บไซต์นี้'
      textElement7.innerText = 'รายละเอียดเพิ่มเติม'
      textElement8.innerText = '3 Check'
      textElement9.innerText = 'เช็คจุดขึ้นวิน'
      textElement10.innerText = 'สามารถที่จะดูจุดขึ้นพี่วิน ในแต่ละจุดภายในมหาวิทยาลัย'
      textElement11.innerText = 'เช็คราคาพี่วิน'
      textElement12.innerText = 'สามารถเช็คราคาวินจากจุดขึ้นวินไปตึกต่าง ๆ ภายในมหาวิทยาลัย'
      textElement13.innerText = 'เช็คข้อมูลเบื้องต้นของพี่วิน'
      textElement14.innerText = 'เช็คข้อมูลเบื้องต้นของพี่วินอาทิ หมายเลขประจำตัว เลขคิววิน และเลขป้ายทะเบียนรถของพี่ ๆ วิน'
      textElement15.innerText = 'พื้นที่ให้บริการ'
      textElement16.innerText = 'สะดวก'
      textElement17.innerText = 'สามารถเช็คได้ถึง 3 อย่าง<br><br><br>'
      textElement18.innerText = 'ปลอดภัย'
      textElement19.innerText = 'จดทะเบียนพี่วินให้เป็นป้ายเหลืองทุกคันและขึ้นในระบบเว็บไซต์<br><br>'
      textElement20.innerText = 'มีมาตรฐาน'
      textElement21.innerText = 'ราคาเป็นมาตรฐานพี่วินป้ายเหลืองทุกคัน<br><br><br>'
      textElement22.innerText = 'ร้องเรียน : '
      textElementfooter.innerText = '©️ 2568 สภานักศึกษา มหาวิทยาลัยธรรมศาสตร์ สงวนลิขสิทธิ์'
    }
  }