function changeLanguage() {
    var languageSelect = document.getElementById('language');
    var language = languageSelect.options[languageSelect.selectedIndex].value;
    var textElement = document.getElementById('text');
    var textElement1 = document.getElementById('text1');
    var textElement2 = document.getElementById('text2');
    var textElement3 = document.getElementById('text3');
    var textElement4 = document.getElementById('text4');
    var textElement5 = document.getElementById('text5');
    var textElement6 = document.getElementById('text6');
    var textElement7 = document.getElementById('text7');
    var textElement8 = document.getElementById('text8');
    var textElement9 = document.getElementById('text9');
    var textElement10 = document.getElementById('text10');
    var textElement11 = document.getElementById('text11');
    var textElement12 = document.getElementById('text12');
    var textElement13 = document.getElementById('text13');
    var textElement14 = document.getElementById('text14');
    var textElement15 = document.getElementById('text15');
    var textElement16 = document.getElementById('text16');
    var textElement17 = document.getElementById('text17');
    var textElement18 = document.getElementById('text18');
    var textElement19 = document.getElementById('text19');
    var textElement20 = document.getElementById('text20');
    var textElement21 = document.getElementById('text21');
    var textElement22 = document.getElementById('text22');
    var textElementfooter = document.getElementById('footer');

    if (language === 'en') {
      textElement.innerText = 'Call Pwin'
      textElement1.innerText = 'Help Center'
      textElement2.innerText = 'Booking Now'
      textElement3.innerText = 'Call Pwin for no more than 15 ฿ throughout the university.';
      textElement4.innerText = 'Get Started'
      textElement5.innerText = 'Convenient Safe and Standardized'
      textElement6.innerText = 'Service to call PWin is a service for students of Thammasat University, Rangsit Center In calling PWin to write within the university and It is a platform to make complaints. You can call PWin or reserve a time to call on this website.'
      textElement7.innerText = 'More details'
      textElement8.innerText = 'How to use'
      textElement9.innerText = 'Pinned'
      textElement10.innerText = 'Choose pick-up point'
      textElement11.innerText = 'Choose payment method'
      textElement12.innerText = 'Choose payment method'
      textElement13.innerText = 'Waiting for PWin to come pick me up'
      textElement14.innerText = 'Stand and wait at the pinpoint'
      textElement15.innerText = 'Service area'
      textElement16.innerText = 'Convenient'
      textElement17.innerText = 'Easy to use in just 3 steps'
      textElement18.innerText = 'Secure'
      textElement19.innerText = 'Register PWin as a yellow plate for every car and show it in the website system'
      textElement20.innerText = 'Standard'
      textElement21.innerText = 'Price is standard with PWin yellow label for every car.'
      textElement22.innerText = 'Complaint : '
      textElementfooter.innerText = '©️ 2024 Dome As Home. All rights reserved.'
    } else if (language === 'th') {
      textElement.innerText = 'เรียกพี่วิน'
      textElement1.innerText = 'ศูนย์ช่วยเหลือ'
      textElement2.innerText = 'จองตอนนี้'
      textElement3.innerText = 'เรียกพี่วินไม่เกิน 15 ฿ ทั่วมหาวิทยาลัย'
      textElement4.innerText = 'เริ่มต้น'
      textElement5.innerText = 'สะดวก ปลอดภัย มีมาตรฐาน'
      textElement6.innerText = 'บริการเรียกพี่วิน คือบริการสำหรับนักศึกษามหาวิทยาลัยธรรมศาตร์ศูนย์รังสิต ในการเรียกพี่วินเขียนภายในมหาวิทยาลัยและ เป็นแพลตฟอร์มในการร้องเรียน โดยสามารถเรียกพี่วินหรือจองเวลาในการเรียกได้ภายในเว็บไซต์นี้'
      textElement7.innerText = 'รายละเอียดเพิ่มเติม'
      textElement8.innerText = 'วิธีใช้งาน'
      textElement9.innerText = 'ปักหมุด'
      textElement10.innerText = 'เลือกจุดรับส่ง'
      textElement11.innerText = 'เลือกวิธีชำระ'
      textElement12.innerText = 'เลือกวิธีชำระค่าบริการ'
      textElement13.innerText = 'รอพี่วินมารับ'
      textElement14.innerText = 'ยืนรอตามจุดที่ปักหมุด'
      textElement15.innerText = 'พื้นที่ให้บริการ'
      textElement16.innerText = 'สะดวก'
      textElement17.innerText = 'ใช้งานง่ายเพียง 3 ขั้นตอน<br><br><br>'
      textElement18.innerText = 'ปลอดภัย'
      textElement19.innerText = 'จดทะเบียนพี่วินให้เป็นป้ายเหลืองทุกคันและขึ้นในระบบเว็บไซต์<br><br>'
      textElement20.innerText = 'มีมาตรฐาน'
      textElement21.innerText = 'ราคาเป็นมาตรฐานพี่วินป้ายเหลืองทุกคัน<br><br><br>'
      textElement22.innerText = 'ร้องเรียน : '
      textElementfooter.innerText = '©️ 2567 พรรคคนกันเอง สงวนลิขสิทธิ์'
    }
  }